- .gitignore
gitignore
- .env 제거
- dist 폴더 제거
> gitfix : " gitignore 수정 "

- src/session/userSession.ts
소켓 정보 {socket.id : socekt}
session 파일 생성
> add 소켓 정보 담을 session userSession

- src/class/server.ts
- src/interface/interface.ts
customScoket
- id 프로퍼티 추가
- 클라 접속하면 id에 uuid를 이용해 값 할당
> fix : " customSocket 수정 "

- src/protobuf/gamePacket.proto
RoomData에
int 64라고 되어있어야 할 부분이
string라고 되어있음
> bugfix 자료형 수정

- src/handlers/handlerMethod.ts
- src/session/socketSession.ts
- src/session/userSession.ts
> 일부 파일 이름 변경 및 공통 함수 변경

- src/events/onData.ts
- src/events/onEnd.ts
- src/handlers/handlerMethod.ts
- src/handlers/user/loginHandler.ts
- src/interface/interface.ts
- src/session/socketSession.ts
socketSession 파일 리팩토링
interface 파일 리팩토링
loginHandler 파일 리팩토링
onData 파일 리팩토링
handlerMethod 파일 리팩토링
onEnd 파일 함수 기능 추가
> 파일 업데이트 및 리팩토링

- src/handlers/handlerMethod.ts
- src/handlers/room/getRoomListHandler.ts
getRoomListHandler
- 방 목록 얻어서 클라에게 전송
> update : " getRoomListHandler 수정 " closes #8

- src/handlers/handlerMethod.ts
- src/handlers/room/getRoomListHandler.ts
- src/handlers/room/joinRandomRoomHandler.ts
- src/handlers/room/joinRoomHandler.ts
- src/handlers/user/loginHandler.ts
- src/main.ts
main에 들어간 실험용 함수 제거 및 프로젝트 내 import 전체적으로 정리
> refactor project

- src/handlers/room/createRoomHandler.ts
createRoomHandler
- 처음 방이 생성될때, gRoomId을 증가 ( 누락 됐었음 )
- sendPacket 한번 호출하도록 수정
> fix : " createRoomHandler 수정 "

- src/handlers/room/createRoomHandler.ts
> bugfix createRoomHnadler

- src/config/config.ts
- src/handlers/game/gameStartHandler.ts
Reverts rettytnova/sur5val_Server#59
> Revert "fix gameStartHandler 수정"

- src/config/config.ts
- src/handlers/game/gameStartHandler.ts
fix gameStartHandler 랜덤 스폰 적용
update config 스폰포인트 매핑 추가
> Fix  dev gameStartHandler

- src/handlers/handlerMethod.ts
- src/handlers/notification/monsterAttack.ts
- src/handlers/notification/monsterMove.ts
- src/handlers/notification/monsterSpawn.ts
몬스터가 건물 안쪽까지 움직이려 하여 움직임이 어색한 부분 수정 → 건물 안쪽으로는 안 움직이도록 경로를 설정할 수 있게 monsterMoveAi 함수 수정
> refactor monsterMove

- src/handlers/enumTyps.ts
> refactor enumType

- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/user/loginHandler.ts
- src/interface/interface.ts
> refactor potion

- src/handlers/coreMethod/monsterMove.ts
- src/handlers/game/gamePrepareHandler.ts
> bugfix manyRooms

- src/config/config.ts
- src/handlers/card/useCardHandler.ts
- src/handlers/coreMethod/monsterMove.ts
- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/game/gamePrepareHandler.ts
- src/handlers/game/gameStartHandler.ts
- src/handlers/game/reactionHandler.ts
- src/handlers/handlerIndex.ts
- src/handlers/notification/gameEnd.ts
- src/handlers/room/createRoomHandler.ts
- src/handlers/room/getRoomListHandler.ts
- src/handlers/user/reactionHandler.ts
죽은 적에게 스킬 사용 가능 버그 수정
게임 종료 함수 위치 이동
게임 종료 handler 생성
몬스터 밸런스 조절 및 console.log 정리
> refactor project Code

- src/handlers/card/useCardHandler.ts
- src/handlers/coreMethod/monsterAttack.ts
- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/game/gamePrepareHandler.ts
- src/handlers/user/loginHandler.ts
- src/interface/interface.ts
- src/protobuf/gamePacket.proto
- src/protobuf/protocol.proto
공격력, 방어력, 최대체력, mp 등 character가 전해줄 패킷 정의 및 데이터 수정
> Feature  character

- src/events/onEnd.ts
- src/handlers/card/useCardHandler.ts
- src/handlers/coreMethod/fleaMarketCardCreate.ts
- src/handlers/coreMethod/monsterAttack.ts
- src/handlers/coreMethod/monsterMove.ts
- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/enumTyps.ts
- src/handlers/game/gameEndHandler.ts
- src/handlers/game/gamePrepareHandler.ts
- src/handlers/game/gameStartHandler.ts
- src/handlers/handlerMethod.ts
- src/handlers/market/fleaMarketItemSelectHandler.ts
- src/handlers/market/fleaMarketOpenHandler.ts
- src/handlers/notification/gameEnd.ts
- src/handlers/notification/userUpdate.ts
- src/handlers/room/createRoomHandler.ts
- src/handlers/room/getRoomListHandler.ts
- src/handlers/room/joinRandomRoomHandler.ts
- src/handlers/room/joinRoomHandler.ts
- src/handlers/room/leaveRoomHandler.ts
- src/handlers/user/loginHandler.ts
- src/handlers/user/positionUpdateHandler.ts
- src/session/shoppingSession.ts
플리마켓에서 상품을 구매하는 방식으로  변경되어 함수 로직 대량 변경
gameEnd winType에 따른 문구가 client에 만들어짐에 따라 winRoleType를 조건에 맞게 주도록 변경
카드 설명 및 카드 이름 추가, 밸런스 조절, shoppingSessions 추가
새로 만들어진 socketSessions가 종료 시 삭제되도록 함수 변경
getUserBySocket 함수를 getUserIdBySocket 로 변경 및 해당 함수사용하는 로직들 모두 변경
유저 상태 업데이트 notification함수에 쇼핑중인 유저의 popup창을 다시 띄워주도록 함수 변경
setinterval 내부에서 rooms를 불러와서 실시간으로 바뀐 능력치 적용안되던 bug 수정
일부 밸런스 조절 및 공격시 몬스터 공격력보다 피격자의 방어력이 높을 경우 체력이 차는 버그 수정
> flea market 함수 변

- src/handlers/notification/userUpdate.ts
merge전에 주석처리했던 코드 실수로 주석 뺀것 다시 넣기
> refactor userUpdate

- src/config/config.ts
> docs : " config.ts 수정 "

- src/chattingServer/handlers/jobHandlers/room/chattingJoinRoomJobHandler.ts
- src/chattingServer/handlers/packetHandlers/room/chattingJoinRoomReqHandler.ts
ChattingJoinRoomHandler ( 채팅 방 참가 요청 ) 추가
ChattingJoinRoomJobHandler ( 채팅 방 참가 요청 잡 처리 ) 추가
> add : " ChattingJoinRoomHandler, ChattingJoinRoomJobHandler 추가 "

- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/room/createRoomHandler.ts
- src/handlers/user/loginHandler.ts
- src/interface/interface.ts
- src/protobuf/gamePacket.proto
- src/protobuf/protocol.proto
UserData
- email 추가
RoomData
- ownerEmail 추가 ( 채팅 서버에서 사용 )
- 방장 이메일
> fix : " UserData, RoomData 수정 "

- src/handlers/card/useCardHandler.ts
- src/handlers/game/gameStartHandler.ts
- src/handlers/notification/gameEnd.ts
- src/interface/interface.ts
- src/protobuf/gamePacket.proto
- src/protobuf/protocol.proto
상대 공격 로직에 보스몬스터가 죽었을 경우 처리 로직 추가
> add useCardHandler

- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/game/gamePrepareHandler.ts
- src/handlers/game/gameStartHandler.ts
- src/handlers/user/loginHandler.ts
- src/interface/interface.ts
보내는 패킷 내용, mp 관리하는 객체를 통해 계산하는 방법 수정
> fix : mpRecovery

- src/config/config.ts
- src/handlers/card/useCardHandler.ts
- src/handlers/market/fleaMarketItemSelectHandler.ts
- src/handlers/room/leaveRoomHandler.ts
> add coodDown

- src/class/server.ts
- src/database/databaseManager.ts
- src/database/schema.sql
- src/database/user/user.queries.ts
databaseManager
- DB 에서 캐릭터 초기 스탯 정보, 캐릭터 레벨업 스탯 정보, 소비품 정보, 장비 정보, 몬스터 정보, 상점 목록 정보, 게임 초기 정보 가져오기 추가
server
- start() 수정
- 정보 가져오기
> add : " DB에서 자료 가져오기 추가 "

- src/handlers/card/useCardHandler.ts
- src/handlers/coreMethod/monsterReward.ts
- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/game/gameStartHandler.ts
> fix useCardHandler

- src/handlers/user/positionUpdateHandler.ts
> fix positionUpdateHandler

- src/class/server.ts
- src/config/config.ts
- src/database/schema.sql
- src/database/user/query.sql
- src/database/user/user.queries.ts
- src/handlers/card/useCardHandler.ts
- src/handlers/coreMethod/fleaMarketCardCreate.ts
- src/handlers/coreMethod/monsterAttack.ts
- src/handlers/coreMethod/monsterReward.ts
- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/game/gamePrepareHandler.ts
- src/handlers/game/gameStartHandler.ts
- src/handlers/market/fleaMarketItemSelectHandler.ts
- src/handlers/notification/gameEnd.ts
- src/handlers/user/loginHandler.ts
- src/interface/interface.ts
상수 값으로 하드코딩 되어있던 데이터들을 DB Data에 연동되도록 전체적인 파일들의 로직 변경
> add DataBase

- src/handlers/game/gameStartHandler.ts
- src/handlers/room/joinRandomRoomHandler.ts
- src/handlers/room/joinRoomHandler.ts
> fix setRedisData

- src/handlers/card/useCardHandler.ts
> fix balance

- src/events/onClose.ts
- src/events/onEnd.ts
- src/handlers/card/useCardHandler.ts
- src/handlers/coreMethod/monsterAttack.ts
- src/handlers/coreMethod/monsterMove.ts
- src/handlers/coreMethod/monsterSpawn.ts
- src/handlers/game/gameStartHandler.ts
- src/handlers/market/fleaMarketItemSelectHandler.ts
- src/handlers/notification/gameEnd.ts
- src/handlers/user/loginHandler.ts
캐릭터와 함께 싸우는 정령 버프 기능의 함수 추가
deleteBuff 기능 추가
settimeout / setInterval를 쓰는 함수들 해당 함수가 시작되는 시점에 데이터를 받아오도록 수정
monsterAttack, monsterMove, monsterSpawn 함수에 roomData와 characterPosition가 일치하지 않는 간헐적인 버그 찾기위해 서버를 멈추고 로그를 띄우는 함수를 추가
게임 종료 시점에 이미 게임을 종료한 유저를 해당 게임방에서 삭제하는 기능에 - 아래의 상황 검사하여 실행하는 기능 추가
1.삭제 시점에 방에 남은 인원이 없을경우 방 삭제 기능
2. 삭제된 유저 중 방장이 있을 경우 방장을 넘겨주는 기능
> add useCardHandler attackArea(정령 소환 버프 기능)

- src/config/config.ts
- src/handlers/enumTyps.ts
- src/handlers/notification/globalMessageSend.ts
- src/protobuf/gamePacket.proto
- src/protobuf/packetNames.ts
- src/protobuf/protocol.proto
- src/protobuf/response.proto
globalMessageSend 추가
- globalMessageRoomSend ( 방안에 있는 유저들에게 전역 메세지 전송 )
- globalMessageUserSend ( 유저에게 전역 메세지 전송 )
> add : " 전역 메세지 전송 기능 추가 "

- src/handlers/card/useCardHandler.ts
- src/handlers/room/createRoomHandler.ts
- src/handlers/room/getRoomListHandler.ts
- src/handlers/room/joinRandomRoomHandler.ts
- src/handlers/room/joinRoomHandler.ts
- src/handlers/room/leaveRoomHandler.ts
- src/handlers/user/loginHandler.ts
- src/packet/createPacket.ts
재 로그인 시 게임에 바로 들어갈 수 있도록 로직 변경
success 0,1 을 false, true로 변경
> fix 재 로그인 시 게임 진입

- src/handlers/card/useCardHandler.ts
- src/handlers/market/fleaMarketItemBuyHandler.ts
fix useCardHandler.ts
fix fleaMarketItemBuyHandler.ts
카드 관련 간단 수정
> fix 카드 장착 로직 오류 개선

- src/events/onChattingServerOnData.ts
ChattingServerOnData
- 채팅서버에서 온 데이터 읽어오기 ( 게임서버에 추가 )
> add : " ChattingServerOnData 추가 "

- src/dummyClient/dummyClient.ts
dummyClient 수정
- 콘솔로 더미 생성, 회원가입, 로그인 조정할 수 있게 바꿈
> fix : " 더미 클라 수정 "

- src/config/config.ts
- src/protobuf/gamePacket.proto
- src/protobuf/packetNames.ts
- src/protobuf/protocol.proto
- src/protobuf/request.proto
protocol
- SpawnPositionSend 프로토콜
> fix : " SpawnPositionSend 프로토콜 추가 "

- src/database/databaseManager.ts
- src/database/schema.sql
- src/database/user/user.queries.ts
- src/gameServer/handlers/card/useCardHandler.ts
- src/gameServer/handlers/handlerIndex.ts
- src/gameServer/handlers/position/createPositionDataHandler.ts
- src/gameServer/handlers/position/positionUpdateHandler.ts
- src/gameServer/interface/interface.ts
스폰위치 생성 핸들러 추가
타입스크립트 인터페이스 추가
데이터베이스 스폰위치 정보 테이블 추가
> update: spawnPosition.ts

- src/database/databaseManager.ts
- src/gameServer/handlers/position/createPositionDataHandler.ts
- src/gameServer/interface/interface.ts
클라이언트에서 들어온 페이로드를 온전히 받지 못하는 오류 수정
> update: createSpawnPostionData.ts

- src/database/databaseManager.ts
databaseManager
- db Pool 연결 개수 10 -> 60
> fix : " databaseManager 수정 "

- src/chattingServer/class/chattingServer.ts
- src/chattingServer/events/chattingOnClose.ts
- src/chattingServer/handlers/jobHandlers/room/chattingCreateRoomJobHandler.ts
- src/chattingServer/handlers/jobHandlers/room/chattingJoinRoomJobHandler.ts
- src/chattingServer/handlers/jobHandlers/room/chattingLeaveRoomJobHandler.ts
- src/chattingServer/handlers/jobHandlers/user/chattingLoginJobHandler.ts
- src/dummyClient/dummyClient.ts
dummyClient
- 회원가입과 로그인 완료 후 화면 뜨도록 함
> fix : " dummyClient 수정 "

- src/gameServer/class/marketSessions.ts
- src/gameServer/class/server.ts
- src/gameServer/handlers/card/useCardHandlerTwo.ts
- src/gameServer/handlers/coreMethod/fleaMarketCardCreateTwo.ts
- src/gameServer/handlers/coreMethod/monsterAttackTwo.ts
- src/gameServer/handlers/coreMethod/monsterMoveTwo.ts
- src/gameServer/handlers/market/fleaMarketBuyOpenHandlerTwo.ts
- src/gameServer/handlers/market/fleaMarketItemBuyHandlerTwo.ts
- src/gameServer/handlers/market/fleaMarketSelectHandlerTwo.ts
- src/gameServer/handlers/market/fleaMarketSellHandlerTwo.ts
- src/gameServer/handlers/market/fleaMarketSellOpenHandletTwo.ts
- src/gameServer/handlers/notification/userUpdateTwo.ts
- src/main.ts
> redis 데이터 관리를 메모리 session으로변경

- src/gameServer/handlers/user/loginHandler.ts
> fix "비정상 로그인 에러 해결"

- src/gameServer/handlers/coreMethod/monsterSpawn.ts
- src/gameServer/handlers/game/gameStartHandler.ts
밸런스 조절
몬스터 스폰 중 오류 수정
user.getId === user.getId
구문
room.id === roomId
> fix monsterSpawn

- src/chattingServer/handlers/jobHandlers/room/chattingCreateRoomJobHandler.ts
- src/chattingServer/handlers/jobHandlers/room/chattingJoinRoomJobHandler.ts
- src/chattingServer/handlers/packetHandlers/room/chattingCreateRoomReqHandler.ts
- src/chattingServer/handlers/packetHandlers/room/chattingJoinRoomReqHandler.ts
- src/gameServer/handlers/notification/gameEnd.ts
- src/gameServer/handlers/room/joinRoomHandler.ts
joinRoomHandler
- 채팅방 참여 채팅서버에게 보낼때 ownerEmail 누락되어 있는 부분 추가
> fix : " 채팅 방 참여 안되는 부분 수정 "

- src/database/databaseManager.ts
- src/dummyClient/dummyClient.ts
- src/dummyClient/responseHandlers/room/createRoomResponseHandler.ts
- src/dummyClient/responseHandlers/room/getRoomListResponseHandler.ts
- src/dummyClient/responseHandlers/user/gameLoginResponseHandler.ts
- src/gameServer/class/server.ts
- src/gameServer/handlers/user/registerHandler.ts
dummyClient
- 게임 시작을 누르면 접속한 더미 중 30%가 방을 생성 나머지 70%는 방 입장 대기
- this.getRoomListReqInterval 추가 ( 방 목록 요청 interval )
- GameServerCreateRoom() 추가
- 더미 방 생성 요청 전송
- GameServerGetRoomList) 수정
- 방 목록 요청 하는 interval을 getRoomListReqInterval에 저장
> fix : " dummy 방 생성 추가 "
